### ISSUE TITLE
HR

### ISSUE THREAD

**Issue by petardinho** [4773n0x/osu-Tool-CPP#1]
With hardrock it doesnt flip the board for hit scan so it reacts on original position of circles which is obviously bad. Just wanted to notice ;) Apart from that it's awesome, love the hit scan.

Also, are you planning to add more features than just relax and/or enhance it? I can help some too.

**Comment by 4773n0x** [comment]
I know about this and I will add a way to get/change active mods later. After relax is done, I will probably work on auto/aim assist. I'm currently working on calculating stacked note coordinates.
